//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindEFModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NorthwindEFContextContainer : DbContext
    {
        public NorthwindEFContextContainer()
            : base("name=NorthwindEFContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Category> Categories { get; set; }
        public IDbSet<Customer> Customers { get; set; }
        public IDbSet<Employee> Employees { get; set; }
        public IDbSet<InternationalOrder> InternationalOrders { get; set; }
        public IDbSet<OrderDetail> OrderDetails { get; set; }
        public IDbSet<Order> Orders { get; set; }
        public IDbSet<PreviousEmployee> PreviousEmployees { get; set; }
        public IDbSet<Product> Products { get; set; }
        public IDbSet<Region> Regions { get; set; }
        public IDbSet<Supplier> Suppliers { get; set; }
        public IDbSet<Territory> Territories { get; set; }
        public IDbSet<Time> Times { get; set; }
    }
}
