//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace NorthwindEFModel
{
    public class NorthwindEFContext : DbContext
    {
        static NorthwindEFContext()
        {
            //Note: OLAP DB creation is not supported, 
            //so make sure you include 'Database.SetInitializer<YourContext>(null);' in your DbContext
            Database.SetInitializer<NorthwindEFContext>(null);
        }

        NorthwindEFContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
        }

        public static NorthwindEFContext CreateForOfflineOlapCube()
        {
            return new NorthwindEFContext("Name=NorthwindEFOlapOfflineCubeFile");
        }

        public static NorthwindEFContext CreateForOnlineOlapServer()
        {
            return new NorthwindEFContext("Name=NorthwindEFOlapOnlineServer");
        }

        public static NorthwindEFContext CreateForSql()
        {
            return new NorthwindEFContext("Name=NorthwindEFDb");
        }

        public IDbSet<Customer> Customers { get; set; }
        //public IDbSet<InternationalOrder> InternationalOrders { get; set; }
        public IDbSet<OrderDetail> OrderDetails { get; set; }
        public IDbSet<Order> Orders { get; set; }
        //public IDbSet<PreviousEmployee> PreviousEmployees { get; set; }
        //public IDbSet<Time> Times { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Configurations.Add(new OrderDetailConfiguration());
            //Note: use the following line if needed by your cube, our examples do not need this:
            //modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
        }
    }
}